### ISSUE TITLE
Error loading bootstrap.js after upgrade from 0.0.19 to 0.0.27

### ISSUE THREAD

**Issue by Pheil** [mozilla/jpm#266]
After upgrading today my extension does not load due to the following error.  I'm using the latest FF 36.0 beta

`1424441209942   addons.xpi      WARN    Error loading bootstrap.js for jid1-9sWae8KGaLLirw@jetpack:
Module `resource://gre/modules/commonjs/sdk/addon/bootstrap.js` is not found at resource://gre/modul
es/commonjs/sdk/addon/bootstrap.js (resource://gre/modules/commonjs/toolkit/require.js:24) JS Stack
trace: make/require@require.js:24:12 < @jar:file:///C:/Users/pmh/AppData/Local/Temp/2c7ef019-3cd
d-4376-aee0-864c10a0c98c/extensions/jid1-9sWae8KGaLLirw@bootstrap.js:10:23 < @XPIProvider.jsm:4333:1
 < XPI_loadBootstrapScope@XPIProvider.jsm:4333:7 < XPI_callBootstrapMethod@XPIProvider.jsm:4408:1 <
addMetadata@XPIProvider.jsm:3333:1 < XPI_processFileChanges@XPIProvider.jsm:3442:23 < XPI_checkForCh
anges@XPIProvider.jsm:3603:34 < XPI_startup@XPIProvider.jsm:2091:25 < callProvider@AddonManager.jsm:
208:12 < _startProvider@AddonManager.jsm:667:5 < AMI_startup@AddonManager.jsm:824:9 < AMP_startup@Ad
donManager.jsm:2402:5 < AMC_observe@addonManager.js:55:7
1424441209943   addons.xpi      WARN    Exception running bootstrap method install on jid1-9sWae8KGa
LLirw@jetpack: TypeError: this.bootstrapScopes[aAddon.id][aMethod] is not a function (resource://gre
/modules/addons/XPIProvider.jsm:4436:8) JS Stack trace: XPI_callBootstrapMethod@XPIProvider.jsm:4436
:9 < addMetadata@XPIProvider.jsm:3333:1 < XPI_processFileChanges@XPIProvider.jsm:3442:23 < XPI_check
ForChanges@XPIProvider.jsm:3603:34 < XPI_startup@XPIProvider.jsm:2091:25 < callProvider@AddonManager
.jsm:208:12 < _startProvider@AddonManager.jsm:667:5 < AMI_startup@AddonManager.jsm:824:9 < AMP_start
up@AddonManager.jsm:2402:5 < AMC_observe@addonManager.js:55:7`

**Comment by TyDraniu** [comment]
Propably connected with #261, it will not work below FF 38.

**Comment by erikvold** [comment]
@TyDraniu you probably need to upgrade your FF 38, do you have the latest nightly?

**Comment by TyDraniu** [comment]
Sorry, I'm not reporting any issue, just answering @Pheil . I have the latest nightly.

**Comment by erikvold** [comment]
Ah sorry @Pheil ^ ?

**Comment by Pheil** [comment]
@TyDraniu Yup, that looks like it's the problem since I'm using FF36.
